### ISSUE TITLE
Question regarding the NLL term

### ISSUE THREAD

**Issue by mataney** [jxhe/vae-lagging-encoder#3]
Hi, how are you?
Thanks for a great paper git repository.

https://github.com/jxhe/vae-lagging-encoder/blob/d78230aa914ac9965b063a3b2bdc759fb1b820ec/text.py#L433
What is the upside in dividing the losses with `report_num_sents` comparing to returning the mean from both `loss_rc` and `loss_kl`?
From what I understand, this is the same except when we have batches in different sizes (let's say at the end of an epoch). 
I believe returning micro average sounds more like it than macro average.
Am I missing something?
What do you think?

Thanks.
Matan.

**Comment by jxhe** [comment]
Hi Matan,
You are right dividing the losses with `report_num_sents` is equivalent to returning the mean from both `loss_rc` and `loss_kl`, except when we have batches in different sizes, but note that different-size batches might appear multiple times besides the end of an epoch.

This is because our batching policy only puts same-length sentences into a batch:

https://github.com/jxhe/vae-lagging-encoder/blob/d78230aa914ac9965b063a3b2bdc759fb1b820ec/data/text_data.py#L219-L222

Therefore we divide losses with `report_num_sents` just to be more accurate.

We also tried fully random batching in the experiments, the results are slightly better than the reported ones in the paper, but the speed is also slower.

**Comment by jxhe** [comment]
Matan, I am going to close this issue since I didn't hear back from you. If you have additional questions, feel free to re-open this issue.
